//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 新ファイル名を指定して実行.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>エイリアス,詳細,補足,コマンド,管理者権限</string>\r\n  <string>appwiz.cpl,アプリケーションの追加と削除,,appw" +
            "iz.cpl,</string>\r\n  <string>eventvwr,イベントビューア,,eventvwr,</string>\r\n  <string>ine" +
            "tcpl.cpl,インターネットオプション,,inetcpl.cpl,</string>\r\n  <string>ciadv.msc,インデックスサービス,,ci" +
            "adv.msc,</string>\r\n  <string>explorer,エクスプローラ,,explorer,</string>\r\n  <string>pac" +
            "kager,オブジェクトパッケージャ,,packager,</string>\r\n  <string>eudcedit,外字エディタ,,eudcedit,</st" +
            "ring>\r\n  <string>magnify,拡大鏡,,magnify,</string>\r\n  <string>desk.cpl,画面のプロパティ,,de" +
            "sk.cpl,</string>\r\n  <string>control,コントロールパネル,,control,</string>\r\n  <string>cont" +
            "rol admintools,管理ツール,,control admintools,</string>\r\n  <string>control printers,デ" +
            "バイスとプリンタ,,control printers,</string>\r\n  <string>control folders,フォルダオプション,,contr" +
            "ol FOLDERS,</string>\r\n  <string>fsmgmt.msc,共有フォルダ,,fsmgmt.msc,</string>\r\n  <stri" +
            "ng>shrpubw,共有フォルダの作成,,shrpubw,</string>\r\n  <string>clipbrd,クリップブック,,clipbrd,</st" +
            "ring>\r\n  <string>gpedit.msc,グループポリシー,,gpedit.msc,</string>\r\n  <string>joy.cpl,ゲー" +
            "ムコントローラ,,joy.cpl,</string>\r\n  <string>mmc,コンソール,,mmc,</string>\r\n  <string>compmg" +
            "mt.msc,コンピュータの管理,,compmgmt.msc,</string>\r\n  <string>services.msc,サービス,,services." +
            "msc,</string>\r\n  <string>mmsys.cpl,サウンドとオーディオデバイスのプロパティ,,mmsys.cpl,</string>\r\n  " +
            "<string>sndrec32,サウンドレコーダー,,sndrec32,</string>\r\n  <string>sysedit,システムエディタ,,syse" +
            "dit,</string>\r\n  <string>msconfig,システム構成ユーティリティ,,msconfig,</string>\r\n  <string>m" +
            "sinfo32,システム情報,,msinfo32,</string>\r\n  <string>sysdm.cpl,システムのプロパティ,,sysdm.cpl,</" +
            "string>\r\n  <string>wuaucpl.cpl,自動更新,,wuaucpl.cpl,</string>\r\n  <string>certmgr.ms" +
            "c,証明書,,certmgr.msc,</string>\r\n  <string>osk,スクリーンキーボード,,osk,</string>\r\n  <string" +
            ">spider,スパイダ,,spider,</string>\r\n  <string>fxscover,送付状エディタ,,fxscover,</string>\r\n" +
            "  <string>sol,ソリティア,,sol,</string>\r\n  <string>taskmgr,タスクマネージャ,,taskmgr,</string" +
            ">\r\n  <string>intl.cpl,地域と言語のオプション,,intl.cpl,</string>\r\n  <string>winchat,チャット,,w" +
            "inchat,</string>\r\n  <string>cleanmgr,ディスククリーンアップ,,cleanmgr,</string>\r\n  <string>" +
            "dfrg.msc,ディスクデフラグツール,,dfrg.msc,</string>\r\n  <string>diskmgmt.msc,ディスクの管理,,diskmg" +
            "mt.msc,</string>\r\n  <string>devmgmt.msc,デバイスマネージャ,,devmgmt.msc,</string>\r\n  <str" +
            "ing>powercfg.cpl,電源オプション,,powercfg.cpl,</string>\r\n  <string>calc,電卓,,calc,</stri" +
            "ng>\r\n  <string>telephon.cpl,電話とモデムのオプション,,telephon.cpl,</string>\r\n  <string>narr" +
            "ator,ナレータ,,narrator,</string>\r\n  <string>ncpa.cpl,ネットワーク接続,,ncpa.cpl,</string>\r\n" +
            "  <string>netsetup.cpl,ネットワークセットアップウィザード,,netsetup.cpl,</string>\r\n  <string>mshe" +
            "arts,ハーツ,,mshearts,</string>\r\n  <string>hdwwiz.cpl,ハードウェアの追加ウィザード,,hdwwiz.cpl,</" +
            "string>\r\n  <string>perfmon,パフォーマンス,,perfmon,</string>\r\n  <string>timedate.cpl,日付" +
            "と時刻のプロパティ,,timedate.cpl,</string>\r\n  <string>pinball,ピンボール,,pinball,</string>\r\n " +
            " <string>migwiz,ファイルと設定の転送ウィザード,,migwiz,</string>\r\n  <string>sigverif,ファイルの署名と確認" +
            ",,sigverif,</string>\r\n  <string>fonts,フォントフォルダ,,fonts,</string>\r\n  <string>freec" +
            "ell,フリーセル,,freecell,</string>\r\n  <string>appwiz.cpl,プログラムの追加と削除,,appwiz.cpl,</st" +
            "ring>\r\n  <string>dcomcnfg,分散COMの構成のプロパティ,,dcomcnfg,</string>\r\n  <string>mspaint," +
            "ペイント,,mspaint,</string>\r\n  <string>rsop.msc,ポリシーの結果セット,,rsop.msc,</string>\r\n  <s" +
            "tring>sndvol32,ボリュームコントロール,,sndvol32,</string>\r\n  <string>winmine,マインスイーパ,,winmi" +
            "ne,</string>\r\n  <string>main.cpl,マウスのプロパティ,,main.cpl,</string>\r\n  <string>notepa" +
            "d,メモ帳,,notepad,</string>\r\n  <string>charmap,文字コード表,,charmap,</string>\r\n  <string" +
            ">nusrmgr.cpl,ユーザーアカウント,,nusrmgr.cpl,</string>\r\n  <string>accwiz,ユーザー補助の設定ウィザード,," +
            "accwiz,</string>\r\n  <string>utilman,ユーティリティマネージャ,,utilman,</string>\r\n  <string>n" +
            "tmsmgr.msc,リムーバブル記憶領域の管理,,ntmsmgr.msc,</string>\r\n  <string>ntmsoprq.msc,リムーバブル記憶" +
            "領域の操作要求,,ntmsoprq.msc,</string>\r\n  <string>mstsc,リモートデスクトップ接続,,mstsc,</string>\r\n" +
            "  <string>regedit,レジストリエディタ,,regedit,</string>\r\n  <string>secpol.msc,ローカルセキュリティポ" +
            "リシー,,secpol.msc,</string>\r\n  <string>lusrmgr.msc,ローカルユーザとグループ,,lusrmgr.msc,</str" +
            "ing>\r\n  <string>logoff,ログオフ,,logoff,</string>\r\n  <string>wordpad,ワードパット,,wordpad" +
            ",</string>\r\n  <string>drwatson,ワトソン博士,,drwatson,</string>\r\n  <string>msaccess,Ac" +
            "cess,,msaccess,</string>\r\n  <string>ddeshare,DDE共有,,ddeshare,</string>\r\n  <strin" +
            "g>dxdiag,Direct X診断ツール,,dxdiag,</string>\r\n  <string>verifier,Driver Verifier Man" +
            "ager（システム内のドライバ分析）,,verifier,</string>\r\n  <string>excel,Excel,,excel,</string>\r\n" +
            "  <string>iexpress,IExpress（自己解凍書庫作成）,,iexpress,</string>\r\n  <string>iexplorer,I" +
            "nternet Explorer,,iexplorer,</string>\r\n  <string>wupdmgr,Microsoft Update,,wupdm" +
            "gr,</string>\r\n  <string>mrt,Microsoft Windows　悪意のあるソフトウェアの削除ツール,,mrt,</string>\r\n" +
            "  <string>nslookup,nslookup,,nslookup,</string>\r\n  <string>odbcad32,ODBCデータソースアド" +
            "ミニストレータ,,odbcad32,</string>\r\n  <string>outlook,Outlook,,outlook,</string>\r\n  <st" +
            "ring>powerpnt,PowerPoint,,powerpnt,</string>\r\n  <string>telnet,Telnet,,telnet,</" +
            "string>\r\n  <string>visio32,Visio,,visio32,</string>\r\n  <string>wmplayer,Windows " +
            "Media Player,,wmplayer,</string>\r\n  <string>wscript,Windows Script Hostの設定,,wscr" +
            "ipt,</string>\r\n  <string>syskey,Windows XPアカウントデータベースのセキュリティ保護,,syskey,</string>" +
            "\r\n  <string>wscui.msc,Windowsセキュリティセンター,,wscui.msc,</string>\r\n  <string>winver,W" +
            "indowsバージョン情報,,winver,</string>\r\n  <string>firewall.cpl,Windowsファイアウォール,,firewal" +
            "l.cpl,</string>\r\n  <string>wmimgmt.msc,WMI,,wmimgmt.msc,</string>\r\n  <string>win" +
            "word,Word,,winword,</string>\r\n  <string>shell:Startup,ユーザーのスタートアップ,\\Microsoft\\Wi" +
            "ndows\\Start Menu\\Programs\\Startup,shell:Startup,</string>\r\n  <string>shell:Start" +
            " Menu,ユーザーのスタートメニュー,【ホットキ-】\\Microsoft\\Windows\\Start Menu,shell:Start Menu,</stri" +
            "ng>\r\n  <string>shell:Programs,プログラムフォルダ,,shell:Programs,</string>\r\n  <string>she" +
            "ll:Downloads,ダウンロードフォルダ,,shell:Downloads,</string>\r\n  <string>cmd /k ipconfig,コマ" +
            "ンドプロンプト,,cmd /k ipconfig,</string>\r\n  <string>cmd,コマンドプロンプト,,cmd,</string>\r\n  <s" +
            "tring>ms-settings:windowsupdate,WindowsUpdate,,ms-settings:windowsupdate,</strin" +
            "g>\r\n  <string>ms-settings:powersleep,電源とスリープ,,ms-settings:powersleep,</string>\r\n" +
            "  <string>ms-settings:display,ディスプレイ,,ms-settings:display,</string>\r\n  <string>m" +
            "s-settings:printers,プリンターとスキャナ,,ms-settings:printers,</string>\r\n  <string>hosts," +
            "ホストファイル編集,,notepad C:\\Windows\\System32\\drivers\\etc\\hosts,</string>\r\n  <string>sh" +
            "are,共有フォルダ,,D:\\95_share,</string>\r\n  <string>work,ワークフォルダ,,D:\\96_work,</string>\r" +
            "\n  <string>tool,ツールフォルダ,,D:\\97_tool,</string>\r\n  <string>printscreen,キャプチャフォルダ,," +
            "D:\\98_printscreen,</string>\r\n  <string>my,ショートカットキーフォルダ,,D:\\99_my,</string>\r\n  <" +
            "string>environment,環境変数,,rundll32.exe sysdm.cpl EditEnvironmentVariables,</strin" +
            "g>\r\n  <string>kinou,機能の有効化または無効化,,OptionalFeatures.exe,</string>\r\n  <string>UAC," +
            "ユーザー制御,,UserAccountControlSettings.exe,</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection COMMANDS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["COMMANDS"]));
            }
            set {
                this["COMMANDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kidoSetting {
            get {
                return ((bool)(this["kidoSetting"]));
            }
            set {
                this["kidoSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("左上")]
        public string displaySetting {
            get {
                return ((string)(this["displaySetting"]));
            }
            set {
                this["displaySetting"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DB.mdf;Integr" +
            "ated Security=True;Connect Timeout=30")]
        public string DBConnectionString {
            get {
                return ((string)(this["DBConnectionString"]));
            }
        }
    }
}
