//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 新ファイル名を指定して実行.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kidoSetting {
            get {
                return ((bool)(this["kidoSetting"]));
            }
            set {
                this["kidoSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("左上")]
        public string displaySetting {
            get {
                return ((string)(this["displaySetting"]));
            }
            set {
                this["displaySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>eventvwr,イベントビューア,,eventvwr</string>\r\n  <string>inetcpl.cpl,インターネットオプション,," +
            "inetcpl.cpl</string>\r\n  <string>ciadv.msc,インデックスサービス,,ciadv.msc</string>\r\n  <str" +
            "ing>explorer,エクスプローラ,,explorer</string>\r\n  <string>eudcedit,外字エディタ,,eudcedit</st" +
            "ring>\r\n  <string>magnify,拡大鏡,,magnify</string>\r\n  <string>desk.cpl,画面のプロパティ,,des" +
            "k.cpl</string>\r\n  <string>control,コントロールパネル,,control</string>\r\n  <string>control" +
            " admintools,管理ツール,,control admintools</string>\r\n  <string>control printers,デバイスと" +
            "プリンタ,,control printers</string>\r\n  <string>control folders,フォルダオプション,,control FO" +
            "LDERS</string>\r\n  <string>fsmgmt.msc,共有フォルダ,,fsmgmt.msc</string>\r\n  <string>gped" +
            "it.msc,グループポリシー,,gpedit.msc</string>\r\n  <string>joy.cpl,ゲームコントローラ,,joy.cpl</stri" +
            "ng>\r\n  <string>mmc,コンソール,,mmc</string>\r\n  <string>compmgmt.msc,コンピュータの管理,,compmg" +
            "mt.msc</string>\r\n  <string>services.msc,サービス,,services.msc</string>\r\n  <string>m" +
            "msys.cpl,サウンドとオーディオデバイスのプロパティ,,mmsys.cpl</string>\r\n  <string>sndrec32,サウンドレコーダー," +
            ",sndrec32</string>\r\n  <string>sysedit,システムエディタ,,sysedit</string>\r\n  <string>msco" +
            "nfig,システム構成ユーティリティ,,msconfig</string>\r\n  <string>msinfo32,システム情報,,msinfo32</stri" +
            "ng>\r\n  <string>sysdm.cpl,システムのプロパティ,,sysdm.cpl</string>\r\n  <string>wuaucpl.cpl,自" +
            "動更新,,wuaucpl.cpl</string>\r\n  <string>certmgr.msc,証明書,,certmgr.msc</string>\r\n  <s" +
            "tring>osk,スクリーンキーボード,,osk</string>\r\n  <string>spider,スパイダ,,spider</string>\r\n  <s" +
            "tring>fxscover,送付状エディタ,,fxscover</string>\r\n  <string>sol,ソリティア,,sol</string>\r\n  " +
            "<string>taskmgr,タスクマネージャ,,taskmgr</string>\r\n  <string>intl.cpl,地域と言語のオプション,,intl" +
            ".cpl</string>\r\n  <string>winchat,チャット,,winchat</string>\r\n  <string>cleanmgr,ディスク" +
            "クリーンアップ,,cleanmgr</string>\r\n  <string>dfrg.msc,ディスクデフラグツール,,dfrg.msc</string>\r\n " +
            " <string>diskmgmt.msc,ディスクの管理,,diskmgmt.msc</string>\r\n  <string>devmgmt.msc,デバイス" +
            "マネージャ,,devmgmt.msc</string>\r\n  <string>powercfg.cpl,電源オプション,,powercfg.cpl</strin" +
            "g>\r\n  <string>calc,電卓,,calc</string>\r\n  <string>ncpa.cpl,ネットワーク接続,,ncpa.cpl</str" +
            "ing>\r\n  <string>mshearts,ハーツ,,mshearts</string>\r\n  <string>perfmon,パフォーマンス,,perf" +
            "mon</string>\r\n  <string>timedate.cpl,日付と時刻のプロパティ,,timedate.cpl</string>\r\n  <stri" +
            "ng>sigverif,ファイルの署名と確認,,sigverif</string>\r\n  <string>fonts,フォントフォルダ,,fonts</stri" +
            "ng>\r\n  <string>appwiz.cpl,プログラムの追加と削除,,appwiz.cpl</string>\r\n  <string>mspaint,ペイ" +
            "ント,,mspaint</string>\r\n  <string>sndvol32,ボリュームコントロール,,sndvol32</string>\r\n  <stri" +
            "ng>main.cpl,マウスのプロパティ,,main.cpl</string>\r\n  <string>notepad,メモ帳,,notepad</string" +
            ">\r\n  <string>charmap,文字コード表,,charmap</string>\r\n  <string>nusrmgr.cpl,ユーザーアカウント,," +
            "nusrmgr.cpl</string>\r\n  <string>ntmsmgr.msc,リムーバブル記憶領域の管理,,ntmsmgr.msc</string>\r" +
            "\n  <string>ntmsoprq.msc,リムーバブル記憶領域の操作要求,,ntmsoprq.msc</string>\r\n  <string>mstsc," +
            "リモートデスクトップ接続,,mstsc</string>\r\n  <string>regedit,レジストリエディタ,,regedit</string>\r\n  <" +
            "string>secpol.msc,ローカルセキュリティポリシー,,secpol.msc</string>\r\n  <string>lusrmgr.msc,ローカ" +
            "ルユーザとグループ,,lusrmgr.msc</string>\r\n  <string>logoff,ログオフ,,logoff</string>\r\n  <stri" +
            "ng>wordpad,ワードパット,,wordpad</string>\r\n  <string>msaccess,Access,,msaccess</string" +
            ">\r\n  <string>dxdiag,Direct X診断ツール,,dxdiag</string>\r\n  <string>excel,Excel,,excel" +
            "</string>\r\n  <string>iexpress,IExpress（自己解凍書庫作成）,,iexpress</string>\r\n  <string>i" +
            "explorer,Internet Explorer,,iexplorer</string>\r\n  <string>wupdmgr,Microsoft Upda" +
            "te,,wupdmgr</string>\r\n  <string>mrt,Microsoft Windows　悪意のあるソフトウェアの削除ツール,,mrt</st" +
            "ring>\r\n  <string>nslookup,nslookup,,nslookup</string>\r\n  <string>odbcad32,ODBCデー" +
            "タソースアドミニストレータ,,odbcad32</string>\r\n  <string>outlook,Outlook,,outlook</string>\r\n " +
            " <string>powerpnt,PowerPoint,,powerpnt</string>\r\n  <string>telnet,Telnet,,telnet" +
            "</string>\r\n  <string>visio32,Visio,,visio32</string>\r\n  <string>wmplayer,Windows" +
            " Media Player,,wmplayer</string>\r\n  <string>wscui.msc,Windowsセキュリティセンター,,wscui.m" +
            "sc</string>\r\n  <string>winver,Windowsバージョン情報,,winver</string>\r\n  <string>firewal" +
            "l1,Windowsファイアウォール,,firewall.cpl</string>\r\n  <string>firewall2,Windowsファイアウォール(詳" +
            "細),,wf.msc</string>\r\n  <string>winword,Word,,winword</string>\r\n  <string>shell:S" +
            "tartup,ユーザーのスタートアップ,\\Microsoft\\Windows\\Start Menu\\Programs\\Startup,shell:Startup" +
            "</string>\r\n  <string>shell:Start Menu,ユーザーのスタートメニュー,【ホットキ-】\\Microsoft\\Windows\\St" +
            "art Menu,shell:Start Menu</string>\r\n  <string>shell:Programs,プログラムフォルダ,,shell:Pr" +
            "ograms</string>\r\n  <string>shell:Downloads,ダウンロードフォルダ,,shell:Downloads</string>\r" +
            "\n  <string>cmd /k ipconfig,コマンドプロンプト,,cmd /k ipconfig</string>\r\n  <string>cmd,コマ" +
            "ンドプロンプト,,cmd</string>\r\n  <string>ms-settings:windowsupdate,WindowsUpdate,,ms-set" +
            "tings:windowsupdate</string>\r\n  <string>ms-settings:powersleep,電源とスリープ,,ms-setti" +
            "ngs:powersleep</string>\r\n  <string>ms-settings:display,ディスプレイ,,ms-settings:displ" +
            "ay</string>\r\n  <string>ms-settings:printers,プリンターとスキャナ,,ms-settings:printers</st" +
            "ring>\r\n  <string>hosts,ホストファイル編集,,notepad C:\\Windows\\System32\\drivers\\etc\\hosts<" +
            "/string>\r\n  <string>share,共有フォルダ,,D:\\95_share</string>\r\n  <string>work,ワークフォルダ,," +
            "D:\\96_work</string>\r\n  <string>tool,ツールフォルダ,,D:\\97_tool</string>\r\n  <string>prin" +
            "tscreen,キャプチャフォルダ,,D:\\98_printscreen</string>\r\n  <string>my,ショートカットキーフォルダ,,D:\\99" +
            "_my</string>\r\n  <string>environment,環境変数,,rundll32.exe sysdm.cpl EditEnvironment" +
            "Variables</string>\r\n  <string>kinou,機能の有効化または無効化,,OptionalFeatures.exe</string>\r" +
            "\n  <string>UAC,ユーザー制御,,UserAccountControlSettings.exe</string>\r\n  <string>cmd /k" +
            " ipconfig /release,DHCPのIPアドレス解放,,cmd /k ipconfig /release</string>\r\n  <string>c" +
            "md /k ipconfig /renew,DHCPのIPアドレス再取得,,cmd /k ipconfig /renew</string>\r\n  <string" +
            ">cmd /k ipconfig /displaydns,DNSリゾルバキャッシュ表示,,cmd /k ipconfig /displaydns</string" +
            ">\r\n  <string>cmd /k ipconfig /flushdns,DNSリゾルバキャッシュクリア,,cmd /k ipconfig /flushdn" +
            "s</string>\r\n  <string>cmd /k sc query,プロセス表示,,cmd /k sc query</string>\r\n  <strin" +
            "g>cmd /k net view /domain,ドメイン列挙,,cmd /k net view /domain</string>\r\n  <string>cm" +
            "d /k net view /domain:WORKGROUP,WORKGROUPに属するPC一覧,,cmd /k net view /domain:WORKG" +
            "ROUP</string>\r\n  <string>cmd /k net view /all,ワークグループやドメインのPCを一覧表示,,cmd /k net v" +
            "iew /all</string>\r\n  <string>cmd /k route print,ルーティングテーブル表示,,cmd /k route print" +
            "</string>\r\n  <string>cmd /k driverquery /v,ドライバ一覧表示,,cmd /k driverquery /v</stri" +
            "ng>\r\n  <string>cmd /k driverquery /si,ドライバがデジタル署名済かどうか確認,,cmd /k driverquery /si" +
            "</string>\r\n  <string>cmd /k tracert -d ipaddress,名前解決なしのtracert,,cmd /k tracert " +
            "-d ipaddress</string>\r\n  <string>cmd /k nslookup ipaddress dnsSRV,ホスト名をDNSで解決,,c" +
            "md /k nslookup ipaddress dnsSRV</string>\r\n  <string>cmd /k nslookup hostName dns" +
            "SRV,IPアドレスをDNSで解決,,cmd /k nslookup hostName dnsSRV</string>\r\n  <string>cmd /k ne" +
            "tsh advfirewall firewall show rule name=all dir=in type=dynamic,ファイヤーウォールの受信ポートの" +
            "状態一覧,,cmd /k netsh advfirewall firewall show rule name=all dir=in type=dynamic</" +
            "string>\r\n  <string>cmd /k nbtstat -c,NetBIOSリモートキャッシュネームテーブル表示,,cmd /k nbtstat -" +
            "c</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection COMMANDS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["COMMANDS"]));
            }
            set {
                this["COMMANDS"] = value;
            }
        }
    }
}
