//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 新ファイル名を指定して実行.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool kidoSetting {
            get {
                return ((bool)(this["kidoSetting"]));
            }
            set {
                this["kidoSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("左上")]
        public string displaySetting {
            get {
                return ((string)(this["displaySetting"]));
            }
            set {
                this["displaySetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>eventvwr,イベントビューア,,eventvwr,</string>\r\n  <string>inetcpl.cpl,インターネットオプション," +
            ",inetcpl.cpl,</string>\r\n  <string>ciadv.msc,インデックスサービス,,ciadv.msc,</string>\r\n  <" +
            "string>explorer,エクスプローラ,,explorer,</string>\r\n  <string>eudcedit,外字エディタ,,eudcedit" +
            ",</string>\r\n  <string>magnify,拡大鏡,,magnify,</string>\r\n  <string>desk.cpl,画面のプロパテ" +
            "ィ,,desk.cpl,</string>\r\n  <string>control,コントロールパネル,,control,</string>\r\n  <string" +
            ">control admintools,管理ツール,,control admintools,</string>\r\n  <string>control print" +
            "ers,デバイスとプリンタ,,control printers,</string>\r\n  <string>control folders,フォルダオプション,," +
            "control FOLDERS,</string>\r\n  <string>fsmgmt.msc,共有フォルダ,,fsmgmt.msc,</string>\r\n  " +
            "<string>gpedit.msc,グループポリシー,,gpedit.msc,</string>\r\n  <string>joy.cpl,ゲームコントローラ,," +
            "joy.cpl,</string>\r\n  <string>mmc,コンソール,,mmc,</string>\r\n  <string>compmgmt.msc,コン" +
            "ピュータの管理,,compmgmt.msc,</string>\r\n  <string>services.msc,サービス,,services.msc,</str" +
            "ing>\r\n  <string>mmsys.cpl,サウンドとオーディオデバイスのプロパティ,,mmsys.cpl,</string>\r\n  <string>s" +
            "ndrec32,サウンドレコーダー,,sndrec32,</string>\r\n  <string>sysedit,システムエディタ,,sysedit,</str" +
            "ing>\r\n  <string>msconfig,システム構成ユーティリティ,,msconfig,</string>\r\n  <string>msinfo32,シ" +
            "ステム情報,,msinfo32,</string>\r\n  <string>sysdm.cpl,システムのプロパティ,,sysdm.cpl,</string>\r\n" +
            "  <string>wuaucpl.cpl,自動更新,,wuaucpl.cpl,</string>\r\n  <string>certmgr.msc,証明書,,ce" +
            "rtmgr.msc,</string>\r\n  <string>osk,スクリーンキーボード,,osk,</string>\r\n  <string>spider,ス" +
            "パイダ,,spider,</string>\r\n  <string>fxscover,送付状エディタ,,fxscover,</string>\r\n  <string" +
            ">sol,ソリティア,,sol,</string>\r\n  <string>taskmgr,タスクマネージャ,,taskmgr,</string>\r\n  <str" +
            "ing>taskschd.msc,タスクスケジューラ,,taskschd.msc,</string>\r\n  <string>intl.cpl,地域と言語のオプシ" +
            "ョン,,intl.cpl,</string>\r\n  <string>winchat,チャット,,winchat,</string>\r\n  <string>cle" +
            "anmgr,ディスククリーンアップ,,cleanmgr,</string>\r\n  <string>dfrg.msc,ディスクデフラグツール,,dfrg.msc," +
            "</string>\r\n  <string>diskmgmt.msc,ディスクの管理,,diskmgmt.msc,</string>\r\n  <string>dev" +
            "mgmt.msc,デバイスマネージャ,,devmgmt.msc,</string>\r\n  <string>powercfg.cpl,電源オプション,,power" +
            "cfg.cpl,</string>\r\n  <string>calc,電卓,,calc,</string>\r\n  <string>ncpa.cpl,ネットワーク接" +
            "続,,ncpa.cpl,</string>\r\n  <string>mshearts,ハーツ,,mshearts,</string>\r\n  <string>per" +
            "fmon,パフォーマンス,,perfmon,</string>\r\n  <string>timedate.cpl,日付と時刻のプロパティ,,timedate.cp" +
            "l,</string>\r\n  <string>sigverif,ファイルの署名と確認,,sigverif,</string>\r\n  <string>fonts," +
            "フォントフォルダ,,fonts,</string>\r\n  <string>appwiz.cpl,プログラムの追加と削除,,appwiz.cpl,</string" +
            ">\r\n  <string>mspaint,ペイント,,mspaint,</string>\r\n  <string>sndvol32,ボリュームコントロール,,sn" +
            "dvol32,</string>\r\n  <string>main.cpl,マウスのプロパティ,,main.cpl,</string>\r\n  <string>no" +
            "tepad,メモ帳,,notepad,</string>\r\n  <string>charmap,文字コード表,,charmap,</string>\r\n  <st" +
            "ring>nusrmgr.cpl,ユーザーアカウント,,nusrmgr.cpl,</string>\r\n  <string>ntmsmgr.msc,リムーバブル記" +
            "憶領域の管理,,ntmsmgr.msc,</string>\r\n  <string>ntmsoprq.msc,リムーバブル記憶領域の操作要求,,ntmsoprq." +
            "msc,</string>\r\n  <string>mstsc,リモートデスクトップ接続,,mstsc,</string>\r\n  <string>regedit," +
            "レジストリエディタ,,regedit,</string>\r\n  <string>secpol.msc,ローカルセキュリティポリシー,,secpol.msc,</" +
            "string>\r\n  <string>lusrmgr.msc,ローカルユーザとグループ,,lusrmgr.msc,</string>\r\n  <string>lo" +
            "goff,ログオフ,,logoff,</string>\r\n  <string>wordpad,ワードパット,,wordpad,</string>\r\n  <str" +
            "ing>msaccess,Access,,msaccess,</string>\r\n  <string>dxdiag,Direct X診断ツール,,dxdiag," +
            "</string>\r\n  <string>excel,Excel,,excel,</string>\r\n  <string>iexpress,IExpress（自" +
            "己解凍書庫作成）,,iexpress,</string>\r\n  <string>iexplorer,Internet Explorer,,iexplorer,<" +
            "/string>\r\n  <string>wupdmgr,Microsoft Update,,wupdmgr,</string>\r\n  <string>mrt,M" +
            "icrosoft Windows　悪意のあるソフトウェアの削除ツール,,mrt,</string>\r\n  <string>nslookup,nslookup,," +
            "nslookup,</string>\r\n  <string>odbcad32,ODBCデータソースアドミニストレータ,,odbcad32,</string>\r\n" +
            "  <string>outlook,Outlook,,outlook,</string>\r\n  <string>powerpnt,PowerPoint,,pow" +
            "erpnt,</string>\r\n  <string>telnet,Telnet,,telnet,</string>\r\n  <string>visio32,Vi" +
            "sio,,visio32,</string>\r\n  <string>wmplayer,Windows Media Player,,wmplayer,</stri" +
            "ng>\r\n  <string>wscui.msc,Windowsセキュリティセンター,,wscui.msc,</string>\r\n  <string>winve" +
            "r,Windowsバージョン情報,,winver,</string>\r\n  <string>firewall1,Windowsファイアウォール,,firewal" +
            "l.cpl,</string>\r\n  <string>firewall2,Windowsファイアウォール(詳細),,wf.msc,</string>\r\n  <s" +
            "tring>winword,Word,,winword,</string>\r\n  <string>shell:Startup,ユーザーのスタートアップ,\\Mic" +
            "rosoft\\Windows\\Start Menu\\Programs\\Startup,shell:Startup,</string>\r\n  <string>sh" +
            "ell:Start Menu,ユーザーのスタートメニュー,【ホットキ-】\\Microsoft\\Windows\\Start Menu,shell:Start Me" +
            "nu,</string>\r\n  <string>shell:Programs,プログラムフォルダ,,shell:Programs,</string>\r\n  <s" +
            "tring>shell:Downloads,ダウンロードフォルダ,,shell:Downloads,</string>\r\n  <string>cmd /k ip" +
            "config,コマンドプロンプト,,cmd /k ipconfig,</string>\r\n  <string>cmd,コマンドプロンプト,,cmd,</stri" +
            "ng>\r\n  <string>ms-settings:windowsupdate,WindowsUpdate,,ms-settings:windowsupdat" +
            "e,</string>\r\n  <string>ms-settings:powersleep,電源とスリープ,,ms-settings:powersleep,</" +
            "string>\r\n  <string>ms-settings:display,ディスプレイ,,ms-settings:display,</string>\r\n  " +
            "<string>ms-settings:printers,プリンターとスキャナ,,ms-settings:printers,</string>\r\n  <stri" +
            "ng>hosts,ホストファイル編集,,notepad C:\\Windows\\System32\\drivers\\etc\\hosts,</string>\r\n  <" +
            "string>share,共有フォルダ,,D:\\95_share,</string>\r\n  <string>work,ワークフォルダ,,D:\\96_work,<" +
            "/string>\r\n  <string>tool,ツールフォルダ,,D:\\97_tool,</string>\r\n  <string>printscreen,キャ" +
            "プチャフォルダ,,D:\\98_printscreen,</string>\r\n  <string>my,ショートカットキーフォルダ,,D:\\99_my,</str" +
            "ing>\r\n  <string>environment,環境変数,,rundll32.exe sysdm.cpl EditEnvironmentVariable" +
            "s,</string>\r\n  <string>kinou,機能の有効化または無効化,,OptionalFeatures.exe,</string>\r\n  <st" +
            "ring>UAC,ユーザー制御,,UserAccountControlSettings.exe,</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection COMMANDS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["COMMANDS"]));
            }
            set {
                this["COMMANDS"] = value;
            }
        }
    }
}
